apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: default-instance
spec:
  instances: 1
  transaction:
    xaEnabled: false
  db:
    vendor: postgres
    database: keycloak
    host: ${postgresql_server}
    usernameSecret:
      name: keycloak-db-secrets
      key: db_username
    passwordSecret:
      name: keycloak-db-secrets
      key: db_password
  ingress:
    enabled: false
  hostname:
    hostname: ${dns_prefix}keycloak.${private_dnz_zone}
  http:
    tlsSecret: ${dns_prefix}keycloak.${private_dnz_zone}-tls