apiVersion: xlscsde.nhs.uk/v1
kind: SecretsDistribution
metadata:
  name: keycloak-db-secrets
  annotations:
    xlscsde.nhs.uk/secretUsage: "Keycloak DB Credentials"
spec:
  name: keycloak-db-secrets
  secrets:
  - from: KeycloakDbUsername
    to: db_username

  - from: KeycloakDbPassword
    to: db_password
---
apiVersion: xlscsde.nhs.uk/v1
kind: SecretsDistribution
metadata:
  name: ${dns_prefix}keycloak.${private_dnz_zone}-tls
  annotations:
    xlscsde.nhs.uk/secretUsage: "Wildcard Certificate"
spec:
  name: ${dns_prefix}keycloak.${private_dnz_zone}-tls
  type: kubernetes.io/tls
  secrets:
  - from: WildcardCertificate
    to: tls.crt

  - from: WildcardCertificateKey
    to: tls.key