apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: default-instance
spec:
  instances: 1
  transaction:
    xaEnabled: false
  db:
    vendor: mssql
    database: keycloak
    host: ${azure_sql_server}.database.windows.net
    usernameSecret:
      name: keycloak-secrets
      key: db_username
    passwordSecret:
      name: keycloak-secrets
      key: db_password
  ingress:
    enabled: false
  hostname:
    hostname: ${dns_prefix}keycloak.{dns_zone}
  http:
    tlsSecret: ${dns_prefix}keycloak.{dns_zone}-tls