apiVersion: xlscsde.nhs.uk/v1
kind: SecretsDistribution
metadata:
  name: keycloak-db-secrets
  annotations:
    xlscsde.nhs.uk/secretUsage: "Keycloak DB Credentials"
spec:
  name: keycloak-db-secrets
  secrets:
  - from: SqlHostName
    to: db_host_name

  - from: SqlAdministratorLogin
    to: db_username

  - from: SqlAdministratorPassword
    to: db_password
    