apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: keycloak-credentials-sync
  annotations:
    lsc-sde.io/secretUsage: "Keycloak Credentials"
spec:
  provider: azure
  secretObjects:
  - secretName: keycloak-secrets
    type: Opaque
    data:
    - objectName: SqlHostName
      key: db_host_name
    - objectName: SqlAdministratorLogin
      key: db_username
    - objectName: SqlAdministratorPassword
      key: db_password

  - secretName: sandbox-keycloak.xlscsde.nhs.uk-tls
    type: kubernetes.io/tls
    data:
    - objectName: WildcardCertificate
      key: tls.crt
    - objectName: WildcardCertificateKey
      key: tls.key

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "${azure_client_id}"
    keyvaultName: ${azure_keyvault_name}
    tenantId: "${azure_tenant_id}"
    objects: |
        array:
        - |
          objectName: SqlHostName
          objectType: secret
        - |
          objectName: SqlAdministratorLogin
          objectType: secret
        - |
          objectName: SqlAdministratorPassword
          objectType: secret

        - |
          objectName: WildcardCertificate
          objectType: secret

        - |
          objectName: WildcardCertificateKey
          objectType: secret