apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sandbox-keycloak.privatelink.uksouth.azmk8s.io-tls
spec:
  isCA: false
  commonName: sandbox-keycloak.privatelink.uksouth.azmk8s.io
  secretName: sandbox-keycloak.privatelink.uksouth.azmk8s.io-tls
  subject:
    organizations:
    - lsc-sde
  usages: 
  - server auth
  - client auth
  dnsNames: 
  - sandbox-keycloak.privatelink.uksouth.azmk8s.io
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: keycloak-certificate-authority
    kind: ClusterIssuer
    group: cert-manager.io