apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: default-instance
spec:
  instances: 1
  db:
    vendor: postgres
    database: keycloak
    host: lscsdesandbox-sql.database.windows.net
    usernameSecret:
      name: keycloak-secrets
      key: db_username
    passwordSecret:
      name: keycloak-secrets
      key: db_password
  ingress:
    enabled: false
  hostname:
    hostname: sandbox-keycloak.privatelink.uksouth.azmk8s.io
  http:
    tlsSecret: sandbox-keycloak.privatelink.uksouth.azmk8s.io-tls