apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: default-instance
spec:
  instances: 1
  transaction:
    xaEnabled: false
  db:
    vendor: mssql
    database: keycloak
    host: lscsdesandbox-sql.database.windows.net
    usernameSecret:
      name: keycloak-secrets
      key: db_username
    passwordSecret:
      name: keycloak-secrets
      key: db_password
  ingress:
    enabled: false
  hostname:
    hostname: sandbox-keycloak.xlscsde.nhs.uk
  http:
    tlsSecret: sandbox-keycloak.xlscsde.nhs.uk-tls