apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
spec:
  serviceName: postgresql-db-service
  selector:
    matchLabels:
      app: postgresql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
        - name: postgresql-db
          image: postgres:alpine
          volumeMounts:
            - mountPath: /data
              name: cache-volume

            - mountPath: /data/postgresql-db-data
              name: pgdata
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: keycloak-pgsql-password
                  
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: keycloak-pgsql-username

            - name: PGDATA
              value: /data/postgresql-db-data

            - name: POSTGRES_DB
              value: keycloak
      volumes:
        - name: cache-volume
          emptyDir: {}

        - name: pgdata
          persistentVolumeClaim:
            claimName: keycloak-postgres-disk