apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keycloak-awms
rules:
  - apiGroups:
      - xlscsde.nhs.uk
    resources:
      - analyticsworkspaces
      - analyticsworkspacebindings
    verbs:
      - get
      - list

  - apiGroups:
      - xlscsde.nhs.uk
    resources:
      - analyticsworkspacebindings
      - analyticsworkspaces/status
      - analyticsworkspacebindings/status
      - analyticsworkspaces/scale
      - analyticsworkspacebindings/scale
    verbs:
      - patch