apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak.lsc-sde.local-tls
spec:
  isCA: false
  commonName: keycloak.lsc-sde.local
  secretName: keycloak.lsc-sde.local-tls
  subject:
    organizations:
    - lsc-sde
  usages: 
  - server auth
  - client auth
  dnsNames: 
  - keycloak.lsc-sde.local
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: keycloak-certificate-authority
    kind: ClusterIssuer
    group: cert-manager.io