apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-authority
spec:
  isCA: true
  commonName: keycloak local certificate
  secretName: certificate-authority-tls
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: sde
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: certificate-authority
spec:
  ca:
    secretName: certificate-authority-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak.lsc-sde.local-tls
spec:
  isCA: false
  commonName: keycloak.lsc-sde.local
  secretName: keycloak.lsc-sde.local-tls
  subject:
    organizations:
    - lsc-sde
  usages: 
  - server auth
  - client auth
  dnsNames: 
  - keycloak.lsc-sde.local
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: certificate-authority
    kind: Issuer
    group: cert-manager.io