apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: default-instance
spec:
  instances: 1
  db:
    vendor: postgres
    database: keycloak
    host: kubernetes.docker.internal
    usernameSecret:
      name: keycloak-secrets
      key: keycloak-pgsql-username
    passwordSecret:
      name: keycloak-secrets
      key: keycloak-pgsql-password
  ingress:
    enabled: false
  hostname:
    hostname: keycloak.lsc-sde.local