apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak-instance
spec:
  instances: 1
  db:
    vendor: postgres
    database: keycloak
    host: 192.168.254.160
    usernameSecret:
      name: keycloak-secrets
      key: keycloak-pgsql-username
    passwordSecret:
      name: keycloak-secrets
      key: keycloak-pgsql-password
  ingress:
    className: nginx
  http:
    tlsSecret: keycloak.lsc-sde.local-tls
  hostname:
    hostname: keycloak.lsc-sde.local