apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-postgres-disk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hostpath
  volumeMode: Filesystem